
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc.proyecto1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPEN_BRACE = 9;
  public static final int OPEN_PAREN = 7;
  public static final int SEMICOLON = 6;
  public static final int RANGE = 13;
  public static final int IDENTIFIER = 14;
  public static final int UNION_OP = 17;
  public static final int AND_OP = 16;
  public static final int OPERA = 3;
  public static final int XOR_OP = 18;
  public static final int COLON = 5;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int CLOSE_PAREN = 8;
  public static final int CONJ = 2;
  public static final int CLOSE_BRACE = 10;
  public static final int error = 1;
  public static final int ARROW = 11;
  public static final int DIFF_OP = 19;
  public static final int EVALUAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "OPERA",
  "EVALUAR",
  "COLON",
  "SEMICOLON",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "ARROW",
  "COMMA",
  "RANGE",
  "IDENTIFIER",
  "NUMBER",
  "AND_OP",
  "UNION_OP",
  "XOR_OP",
  "DIFF_OP"
  };
}

